version: '3.8'

services:
  poised_pigeon_prod:
    container_name: poised_pigeon_prod
    image: rabbitmq:3.8.16-management
    hostname: poised-pigeon
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data/prod:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs/prod:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672

  poised_pigeon_test:
    container_name: poised_pigeon_test
    image: rabbitmq:3.8.16-management
    hostname: poised-pigeon
    volumes:
      - ./rabbitmq/etc/definitions-test.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq-test.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data/test:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs/test:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    
  test_lns1:
    container_name: test_lns1
    command: python lns-messaging-broker/tests/lns/lns.py
    command: tail -f requirements.txt
    build: 
      context: .
      dockerfile: ./recipes/docker/test_orchestrator.Dockerfile
    environment: 
      - TEST_ORCHESTRATION_PORT=5001
    volumes: 
      - .:/lns-messaging-broker
    network_mode: "host"

  test_lns2:
    container_name: test_lns2
    command: python lns-messaging-broker/tests/lns/lns.py
    build: 
      context: .
      dockerfile: ./recipes/docker/test_orchestrator.Dockerfile
    environment: 
      - TEST_ORCHESTRATION_PORT=5002
    volumes: 
      - .:/lns-messaging-broker
    network_mode: "host"

  test_lns3:
    container_name: test_lns3
    command: python lns-messaging-broker/tests/lns/lns.py
    build: 
      context: .
      dockerfile: ./recipes/docker/test_orchestrator.Dockerfile
    environment: 
      - TEST_ORCHESTRATION_PORT=5003
    volumes: 
      - .:/lns-messaging-broker
    network_mode: "host"
    
  test_client1:
    container_name: test_client1
    command: python lns-messaging-broker/tests/client/client.py
    build: 
      context: .
      dockerfile: ./recipes/docker/test_orchestrator.Dockerfile
    environment: 
      - TEST_ORCHESTRATION_PORT=5011
    volumes: 
      - .:/lns-messaging-broker
    network_mode: "host"
  
  test_client2:
    container_name: test_client2
    command: python lns-messaging-broker/tests/client/client.py
    build: 
      context: .
      dockerfile: ./recipes/docker/test_orchestrator.Dockerfile
    environment: 
      - TEST_ORCHESTRATION_PORT=5012
    volumes: 
      - .:/lns-messaging-broker
    network_mode: "host"

  test_client3:
    container_name: test_client3
    command: python lns-messaging-broker/tests/client/client.py
    build: 
      context: .
      dockerfile: ./recipes/docker/test_orchestrator.Dockerfile
    environment: 
      - TEST_ORCHESTRATION_PORT=5013
    volumes: 
      - .:/lns-messaging-broker
    network_mode: "host"

  test_orchestrator:
    container_name: test_orchestrator
    # command: pytest tests/
    command: tail -f requirements.txt
    build: 
      context: .
      dockerfile: ./recipes/docker/test_orchestrator.Dockerfile
    # depends_on: 
    #   - test_lns1
      # - test_lns2
      # - test_lns3
      # - test_client1
      # - test_client2
      # - test_client3
    volumes: 
      - .:/lns-messaging-broker
    network_mode: "host"
  
  make_messages:
    command: make messages
    build: 
      context: .
      dockerfile: ./recipes/docker/make_messages.Dockerfile
    volumes: 
      - .:/messages
    network_mode: "host"
