# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lnsalerts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lnsalerts.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0flnsalerts.proto\x1a\x19google/protobuf/any.proto\"o\n\x05\x41lert\x12\x0f\n\x07ownerid\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0f\n\x07subcode\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t\x12%\n\x07\x64\x65tails\x18\x05 \x01(\x0b\x32\x14.google.protobuf.Any\"\x1d\n\x06\x41lerts\x12\x13\n\x03\x61ll\x18\x01 \x03(\x0b\x32\x06.Alert\"C\n\x19\x43\x65rtificateExpiredDetails\x12\x0e\n\x06pubkey\x18\x05 \x01(\t\x12\x16\n\x0e\x65xpirationtime\x18\x06 \x01(\x02\"I\n\x1f\x43\x65rtificateAlmostExpiredDetails\x12\x0e\n\x06pubkey\x18\x05 \x01(\t\x12\x16\n\x0e\x65xpirationtime\x18\x06 \x01(\x02\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_ALERT = _descriptor.Descriptor(
  name='Alert',
  full_name='Alert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ownerid', full_name='Alert.ownerid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='Alert.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subcode', full_name='Alert.subcode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='Alert.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='details', full_name='Alert.details', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=157,
)


_ALERTS = _descriptor.Descriptor(
  name='Alerts',
  full_name='Alerts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='all', full_name='Alerts.all', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=188,
)


_CERTIFICATEEXPIREDDETAILS = _descriptor.Descriptor(
  name='CertificateExpiredDetails',
  full_name='CertificateExpiredDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pubkey', full_name='CertificateExpiredDetails.pubkey', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expirationtime', full_name='CertificateExpiredDetails.expirationtime', index=1,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=257,
)


_CERTIFICATEALMOSTEXPIREDDETAILS = _descriptor.Descriptor(
  name='CertificateAlmostExpiredDetails',
  full_name='CertificateAlmostExpiredDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pubkey', full_name='CertificateAlmostExpiredDetails.pubkey', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expirationtime', full_name='CertificateAlmostExpiredDetails.expirationtime', index=1,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=332,
)

_ALERT.fields_by_name['details'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_ALERTS.fields_by_name['all'].message_type = _ALERT
DESCRIPTOR.message_types_by_name['Alert'] = _ALERT
DESCRIPTOR.message_types_by_name['Alerts'] = _ALERTS
DESCRIPTOR.message_types_by_name['CertificateExpiredDetails'] = _CERTIFICATEEXPIREDDETAILS
DESCRIPTOR.message_types_by_name['CertificateAlmostExpiredDetails'] = _CERTIFICATEALMOSTEXPIREDDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Alert = _reflection.GeneratedProtocolMessageType('Alert', (_message.Message,), {
  'DESCRIPTOR' : _ALERT,
  '__module__' : 'lnsalerts_pb2'
  # @@protoc_insertion_point(class_scope:Alert)
  })
_sym_db.RegisterMessage(Alert)

Alerts = _reflection.GeneratedProtocolMessageType('Alerts', (_message.Message,), {
  'DESCRIPTOR' : _ALERTS,
  '__module__' : 'lnsalerts_pb2'
  # @@protoc_insertion_point(class_scope:Alerts)
  })
_sym_db.RegisterMessage(Alerts)

CertificateExpiredDetails = _reflection.GeneratedProtocolMessageType('CertificateExpiredDetails', (_message.Message,), {
  'DESCRIPTOR' : _CERTIFICATEEXPIREDDETAILS,
  '__module__' : 'lnsalerts_pb2'
  # @@protoc_insertion_point(class_scope:CertificateExpiredDetails)
  })
_sym_db.RegisterMessage(CertificateExpiredDetails)

CertificateAlmostExpiredDetails = _reflection.GeneratedProtocolMessageType('CertificateAlmostExpiredDetails', (_message.Message,), {
  'DESCRIPTOR' : _CERTIFICATEALMOSTEXPIREDDETAILS,
  '__module__' : 'lnsalerts_pb2'
  # @@protoc_insertion_point(class_scope:CertificateAlmostExpiredDetails)
  })
_sym_db.RegisterMessage(CertificateAlmostExpiredDetails)


# @@protoc_insertion_point(module_scope)
